*Read in FPED datasets;
libname FPED0518 "D:\nhanes\data\FPED\";
Data FPED_14;	set FPED0518.FPED_1112;		rename FOODCODE = DR1IFDCD;	rename MODCODE = DR1MC;		Run;
Proc export 	data=FPED0518.FPED_1314		outfile = "D:\CF\AnalysisV3\output\Test.xlsx"	DBMS = xlsx	Replace;	Sheet = "FPED1314";		Run;
Proc import 	datafile = "D:\CF\AnalysisV3\output\Test.xlsx"				out = FPED_16	DBMS = xlsx	replace;	sheet = "FPED1314";		Run;
Data FPED_16;	set FPED_16;				rename FOODCODE = DR1IFDCD;	DR1MC = 0;					Run;
Data FPED_18;	set FPED0518.FPED_1516;		rename FOODCODE = DR1IFDCD;	DR1MC = 0;					Run;
Data FPED_20;	set FPED0518.FPED_1720;		rename FOODCODE = DR1IFDCD;	DR1MC = 0;					Run;

Proc sort data=FPED_14;		by DR1IFDCD DR1MC;		Run;
Proc sort data=FPED_16;		by DR1IFDCD DR1MC;		Run;
Proc sort data=FPED_18;		by DR1IFDCD DR1MC;		Run;
Proc sort data=FPED_20;		by DR1IFDCD DR1MC;		Run;

*Break down INDFOOD to be ready for merging;
Proc sort data=Diet_In out=INDFOOD_PROC;	by DR1IFDCD DR1MC;	Run;
Data INDFOOD_PROC_14;		set INDFOOD_PROC;	if SURVEYYR = 14;	Run;
Data INDFOOD_PROC_16;		set INDFOOD_PROC;	if SURVEYYR = 16;	Run;
Data INDFOOD_PROC_18;		set INDFOOD_PROC;	if SURVEYYR = 18;	Run;
Data INDFOOD_PROC_20;		set INDFOOD_PROC;	if SURVEYYR = 20;	Run;

*Merge INDFOOD with FPED;
Data INDFOOD_PROC_14;		merge INDFOOD_PROC_14	(in = a)	FPED_14;	by DR1IFDCD DR1MC;	if a;	Run;
Data INDFOOD_PROC_16;		merge INDFOOD_PROC_16	(in = a)	FPED_16;	by DR1IFDCD DR1MC;	if a;	Run;
Data INDFOOD_PROC_18;		merge INDFOOD_PROC_18	(in = a)	FPED_18;	by DR1IFDCD DR1MC;	if a;	Run;
Data INDFOOD_PROC_20;		merge INDFOOD_PROC_20	(in = a)	FPED_20;	by DR1IFDCD DR1MC;	if a;	Run;

*Resume correct order;
Proc sort data = INDFOOD_PROC_14;		by SEQN DAYREC DR1ILINE;	Run;
Proc sort data = INDFOOD_PROC_16;		by SEQN DAYREC DR1ILINE;	Run;
Proc sort data = INDFOOD_PROC_18;		by SEQN DAYREC DR1ILINE;	Run;
Proc sort data = INDFOOD_PROC_20;		by SEQN DAYREC DR1ILINE;	Run;

*Merge INDFOOD;
Data INDFOOD_PROC;
	merge INDFOOD_PROC_14 INDFOOD_PROC_16 INDFOOD_PROC_18 INDFOOD_PROC_20;
	by SEQN DAYREC DR1ILINE;
Run;

*Calculate FPED for each line;
Data INDFOOD_PROC;
	set INDFOOD_PROC;
	if DR1DRSTZ = 1 then do;
		DR1I_F_CITMLB_CAL			= F_CITMLB * DR1IGRMS 			/ 100;	DR1I_F_OTHER_CAL			= F_OTHER * DR1IGRMS 			/ 100;	DR1I_F_JUICE_CAL 			= F_JUICE * DR1IGRMS 			/ 100;
		DR1I_F_TOTAL_CAL			= F_TOTAL * DR1IGRMS			/ 100;
		DR1I_V_DRKGR_CAL			= V_DRKGR * DR1IGRMS 			/ 100;	DR1I_V_REDOR_TOMATO_CAL		= V_REDOR_TOMATO * DR1IGRMS 	/ 100;	DR1I_V_REDOR_OTHER_CAL		= V_REDOR_OTHER * DR1IGRMS 		/ 100;
		DR1I_V_REDOR_TOTAL_CAL		= V_REDOR_TOTAL * DR1IGRMS 		/ 100;	DR1I_V_STARCHY_POTATO_CAL	= V_STARCHY_POTATO * DR1IGRMS 	/ 100;	DR1I_V_STARCHY_OTHER_CAL	= V_STARCHY_OTHER * DR1IGRMS 	/ 100;
		DR1I_V_STARCHY_TOTAL_CAL	= V_STARCHY_TOTAL * DR1IGRMS	/ 100;	DR1I_V_OTHER_CAL			= V_OTHER * DR1IGRMS 			/ 100;	DR1I_V_TOTAL_CAL			= V_TOTAL * DR1IGRMS 			/ 100;
		DR1I_V_LEGUMES_CAL			= V_LEGUMES * DR1IGRMS 			/ 100;	DR1I_G_WHOLE_CAL			= G_WHOLE * DR1IGRMS 			/ 100;	DR1I_G_REFINED_CAL			= G_REFINED * DR1IGRMS 			/ 100;
		DR1I_G_TOTAL_CAL			= G_TOTAL * DR1IGRMS 			/ 100;	DR1I_PF_MEAT_CAL			= PF_MEAT * DR1IGRMS 			/ 100;	DR1I_PF_CUREDMEAT_CAL		= PF_CUREDMEAT * DR1IGRMS 		/ 100;
		DR1I_PF_ORGAN_CAL			= PF_ORGAN * DR1IGRMS 			/ 100;	DR1I_PF_POULT_CAL			= PF_POULT * DR1IGRMS 			/ 100;	DR1I_PF_SEAFD_HI_CAL		= PF_SEAFD_HI * DR1IGRMS 		/ 100;
		DR1I_PF_SEAFD_LOW_CAL		= PF_SEAFD_LOW * DR1IGRMS		/ 100;	DR1I_PF_MPS_TOTAL_CAL		= PF_MPS_TOTAL * DR1IGRMS	 	/ 100;	DR1I_PF_EGGS_CAL			= PF_EGGS * DR1IGRMS 			/ 100;
		DR1I_PF_SOY_CAL				= PF_SOY * DR1IGRMS 			/ 100;	DR1I_PF_NUTSDS_CAL			= PF_NUTSDS * DR1IGRMS 			/ 100;	DR1I_PF_LEGUMES_CAL			= PF_LEGUMES * DR1IGRMS 		/ 100;
		DR1I_PF_TOTAL_CAL			= PF_TOTAL * DR1IGRMS 			/ 100;	DR1I_D_MILK_CAL				= D_MILK * DR1IGRMS 			/ 100;	DR1I_D_YOGURT_CAL			= D_YOGURT * DR1IGRMS 			/ 100;
		DR1I_D_CHEESE_CAL			= D_CHEESE * DR1IGRMS 			/ 100;	DR1I_D_TOTAL_CAL			= D_TOTAL * DR1IGRMS			/ 100;	DR1I_OILS_CAL 				= OILS * DR1IGRMS 				/ 100;
		DR1I_SOLID_FATS_CAL			= SOLID_FATS * DR1IGRMS		 	/ 100;	DR1I_ADD_SUGARS_CAL			= ADD_SUGARS * DR1IGRMS 		/ 100;	DR1I_A_DRINKS_CAL			= A_DRINKS * DR1IGRMS 			/ 100;
	end;
Run;
Data INDFOOD_OUT;
	set INDFOOD_PROC;
	drop	F_CITMLB 			F_OTHER 			F_JUICE			F_TOTAL
			V_DRKGR				V_REDOR_TOMATO		V_REDOR_OTHER	V_REDOR_TOTAL		V_STARCHY_POTATO		V_STARCHY_OTHER
			V_STARCHY_TOTAL		V_OTHER				V_TOTAL			V_LEGUMES			
			G_WHOLE				G_REFINED			G_TOTAL			
			PF_MEAT				PF_CUREDMEAT		PF_ORGAN		PF_POULT			PF_SEAFD_HI				PF_SEAFD_LOW		
			PF_MPS_TOTAL		PF_EGGS				PF_SOY			PF_NUTSDS			PF_LEGUMES				PF_TOTAL			
			D_MILK				D_YOGURT			D_CHEESE		D_TOTAL
			OILS				SOLID_FATS			ADD_SUGARS		A_DRINKS;
Run;
Proc datasets;		delete FPED_14	FPED_16	FPED_18	FPED_20	INDFOOD_PROC INDFOOD_PROC_14	INDFOOD_PROC_16	INDFOOD_PROC_18	INDFOOD_PROC_20;	Run;
Quit;
