Data INDPERS_OUT;
	set INDFOOD_IN;
	by SEQN;
	retain	PERS_D1_GHGE 0				PERS_D2_GHGE 0
			PERS_D1_DGA1_GHGE	0		PERS_D1_DGA2_GHGE	0			PERS_D1_DGA3_GHGE	0		PERS_D1_DGA4_GHGE	0			PERS_D1_DGA5_GHGE	0			PERS_D1_DGA6_GHGE	0
			PERS_D1_DGA7_GHGE	0		PERS_D1_DGA8_GHGE	0			PERS_D1_DGA9_GHGE	0		PERS_D1_DGA10_GHGE	0			PERS_D1_DGA11_GHGE 0			PERS_D1_DGA12_GHGE 	0
			PERS_D1_DGA13_GHGE	0		PERS_D1_DGA14_GHGE	0			PERS_D1_DGA15_GHGE  0		PERS_D1_DGA16_GHGE  0			PERS_D1_DGA17_GHGE 0			PERS_D1_DGA18_GHGE	0
			PERS_D1_DGA1_Gram	0		PERS_D1_DGA2_Gram	0			PERS_D1_DGA3_Gram	0		PERS_D1_DGA4_Gram	0			PERS_D1_DGA5_Gram	0			PERS_D1_DGA6_Gram	0
			PERS_D1_DGA7_Gram	0		PERS_D1_DGA8_Gram	0			PERS_D1_DGA9_Gram	0		PERS_D1_DGA10_Gram	0			PERS_D1_DGA11_Gram 0			PERS_D1_DGA12_Gram 	0
			PERS_D1_DGA13_Gram	0		PERS_D1_DGA14_Gram	0			PERS_D1_DGA15_Gram  0		PERS_D1_DGA16_Gram  0			PERS_D1_DGA17_Gram 0			PERS_D1_DGA18_Gram	0

			PERS_D2_DGA1_GHGE	0		PERS_D2_DGA2_GHGE	0			PERS_D2_DGA3_GHGE	0		PERS_D2_DGA4_GHGE	0			PERS_D2_DGA5_GHGE	0			PERS_D2_DGA6_GHGE	0
			PERS_D2_DGA7_GHGE	0		PERS_D2_DGA8_GHGE	0			PERS_D2_DGA9_GHGE	0		PERS_D2_DGA10_GHGE	0			PERS_D2_DGA11_GHGE 0			PERS_D2_DGA12_GHGE 	0
			PERS_D2_DGA13_GHGE	0		PERS_D2_DGA14_GHGE	0			PERS_D2_DGA15_GHGE  0		PERS_D2_DGA16_GHGE  0			PERS_D2_DGA17_GHGE 0			PERS_D2_DGA18_GHGE	0
			PERS_D2_DGA1_Gram	0		PERS_D2_DGA2_Gram	0			PERS_D2_DGA3_Gram	0		PERS_D2_DGA4_Gram	0			PERS_D2_DGA5_Gram	0			PERS_D2_DGA6_Gram	0
			PERS_D2_DGA7_Gram	0		PERS_D2_DGA8_Gram	0			PERS_D2_DGA9_Gram	0		PERS_D2_DGA10_Gram	0			PERS_D2_DGA11_Gram 0			PERS_D2_DGA12_Gram 	0
			PERS_D2_DGA13_Gram	0		PERS_D2_DGA14_Gram	0			PERS_D2_DGA15_Gram  0		PERS_D2_DGA16_Gram  0			PERS_D2_DGA17_Gram 0			PERS_D2_DGA18_Gram	0
			DR1T_F_CITMLB_CAL 0			DR1T_F_OTHER_CAL 0				DR1T_F_JUICE_CAL 0	
			DR1T_F_TOTAL_CAL 0			DR1T_V_DRKGR_CAL 0				DR1T_V_REDOR_TOMATO_CAL 0	DR1T_V_REDOR_OTHER_CAL 0
			DR1T_V_REDOR_TOTAL_CAL 0	DR1T_V_STARCHY_POTATO_CAL 0		DR1T_V_STARCHY_OTHER_CAL 0	DR1T_V_STARCHY_TOTAL_CAL 0	
			DR1T_V_OTHER_CAL 0			DR1T_V_TOTAL_CAL 0				DR1T_V_LEGUMES_CAL 0		DR1T_G_WHOLE_CAL 0
			DR1T_G_REFINED_CAL 0		DR1T_G_TOTAL_CAL 0				DR1T_PF_MEAT_CAL 0			DR1T_PF_CUREDMEAT_CAL 0
			DR1T_PF_ORGAN_CAL 0			DR1T_PF_POULT_CAL 0				DR1T_PF_SEAFD_HI_CAL 0		DR1T_PF_SEAFD_LOW_CAL 0
			DR1T_PF_MPS_TOTAL_CAL 0		DR1T_PF_EGGS_CAL 0				DR1T_PF_SOY_CAL 0			DR1T_PF_NUTSDS_CAL 0
			DR1T_PF_LEGUMES_CAL 0		DR1T_PF_TOTAL_CAL 0				DR1T_D_MILK_CAL 0			DR1T_D_YOGURT_CAL 0
			DR1T_D_CHEESE_CAL 0			DR1T_D_TOTAL_CAL 0				DR1T_OILS_CAL 0				DR1T_SOLID_FATS_CAL 0
			DR1T_ADD_SUGARS_CAL 0		DR1T_A_DRINKS_CAL 0
			DR2T_F_CITMLB_CAL 0			DR2T_F_OTHER_CAL 0				DR2T_F_JUICE_CAL 0	
			DR2T_F_TOTAL_CAL 0			DR2T_V_DRKGR_CAL 0				DR2T_V_REDOR_TOMATO_CAL 0	DR2T_V_REDOR_OTHER_CAL 0
			DR2T_V_REDOR_TOTAL_CAL 0	DR2T_V_STARCHY_POTATO_CAL 0		DR2T_V_STARCHY_OTHER_CAL 0	DR2T_V_STARCHY_TOTAL_CAL 0	
			DR2T_V_OTHER_CAL 0			DR2T_V_TOTAL_CAL 0				DR2T_V_LEGUMES_CAL 0		DR2T_G_WHOLE_CAL 0
			DR2T_G_REFINED_CAL 0		DR2T_G_TOTAL_CAL 0				DR2T_PF_MEAT_CAL 0			DR2T_PF_CUREDMEAT_CAL 0
			DR2T_PF_ORGAN_CAL 0			DR2T_PF_POULT_CAL 0				DR2T_PF_SEAFD_HI_CAL 0		DR2T_PF_SEAFD_LOW_CAL 0
			DR2T_PF_MPS_TOTAL_CAL 0		DR2T_PF_EGGS_CAL 0				DR2T_PF_SOY_CAL 0			DR2T_PF_NUTSDS_CAL 0
			DR2T_PF_LEGUMES_CAL 0		DR2T_PF_TOTAL_CAL 0				DR2T_D_MILK_CAL 0			DR2T_D_YOGURT_CAL 0
			DR2T_D_CHEESE_CAL 0			DR2T_D_TOTAL_CAL 0				DR2T_OILS_CAL 0				DR2T_SOLID_FATS_CAL 0
			DR2T_ADD_SUGARS_CAL 0		DR2T_A_DRINKS_CAL 0				DAY1STZ 0					DAY2STZ 0;
	if first.SEQN then do;
		PERS_D1_GHGE = 0;				PERS_D2_GHGE = 0;
		PERS_D1_DGA1_GHGE =	0;			PERS_D1_DGA2_GHGE = 0;			PERS_D1_DGA3_GHGE = 0;			PERS_D1_DGA4_GHGE = 0;			PERS_D1_DGA5_GHGE = 0;			PERS_D1_DGA6_GHGE = 0;
		PERS_D1_DGA7_GHGE = 0;			PERS_D1_DGA8_GHGE = 0;			PERS_D1_DGA9_GHGE = 0;			PERS_D1_DGA10_GHGE = 0;			PERS_D1_DGA11_GHGE = 0;			PERS_D1_DGA12_GHGE = 0;
		PERS_D1_DGA13_GHGE = 0;			PERS_D1_DGA14_GHGE = 0;			PERS_D1_DGA15_GHGE = 0;			PERS_D1_DGA16_GHGE = 0;			PERS_D1_DGA17_GHGE = 0;			PERS_D1_DGA18_GHGE = 0;
		PERS_D1_DGA1_Gram =	0;			PERS_D1_DGA2_Gram = 0;			PERS_D1_DGA3_Gram = 0;			PERS_D1_DGA4_Gram = 0;			PERS_D1_DGA5_Gram = 0;			PERS_D1_DGA6_Gram = 0;
		PERS_D1_DGA7_Gram = 0;			PERS_D1_DGA8_Gram = 0;			PERS_D1_DGA9_Gram = 0;			PERS_D1_DGA10_Gram = 0;			PERS_D1_DGA11_Gram = 0;			PERS_D1_DGA12_Gram = 0;
		PERS_D1_DGA13_Gram = 0;			PERS_D1_DGA14_Gram = 0;			PERS_D1_DGA15_Gram = 0;			PERS_D1_DGA16_Gram = 0;			PERS_D1_DGA17_Gram = 0;			PERS_D1_DGA18_Gram = 0;

		PERS_D2_DGA1_GHGE =	0;			PERS_D2_DGA2_GHGE = 0;			PERS_D2_DGA3_GHGE = 0;			PERS_D2_DGA4_GHGE = 0;			PERS_D2_DGA5_GHGE = 0;			PERS_D2_DGA6_GHGE = 0;
		PERS_D2_DGA7_GHGE = 0;			PERS_D2_DGA8_GHGE = 0;			PERS_D2_DGA9_GHGE = 0;			PERS_D2_DGA10_GHGE = 0;			PERS_D2_DGA11_GHGE = 0;			PERS_D2_DGA12_GHGE = 0;
		PERS_D2_DGA13_GHGE = 0;			PERS_D2_DGA14_GHGE = 0;			PERS_D2_DGA15_GHGE = 0;			PERS_D2_DGA16_GHGE = 0;			PERS_D2_DGA17_GHGE = 0;			PERS_D2_DGA18_GHGE = 0;
		PERS_D2_DGA1_Gram =	0;			PERS_D2_DGA2_Gram = 0;			PERS_D2_DGA3_Gram = 0;			PERS_D2_DGA4_Gram = 0;			PERS_D2_DGA5_Gram = 0;			PERS_D2_DGA6_Gram = 0;
		PERS_D2_DGA7_Gram = 0;			PERS_D2_DGA8_Gram = 0;			PERS_D2_DGA9_Gram = 0;			PERS_D2_DGA10_Gram = 0;			PERS_D2_DGA11_Gram = 0;			PERS_D2_DGA12_Gram = 0;
		PERS_D2_DGA13_Gram = 0;			PERS_D2_DGA14_Gram = 0;			PERS_D2_DGA15_Gram = 0;			PERS_D2_DGA16_Gram = 0;			PERS_D2_DGA17_Gram = 0;			PERS_D2_DGA18_Gram = 0;

		DR1T_F_CITMLB_CAL = 0;			DR1T_F_OTHER_CAL = 0;			DR1T_F_JUICE_CAL = 0;	
		DR1T_F_TOTAL_CAL = 0;			DR1T_V_DRKGR_CAL = 0;			DR1T_V_REDOR_TOMATO_CAL = 0;	DR1T_V_REDOR_OTHER_CAL = 0;
		DR1T_V_REDOR_TOTAL_CAL = 0;		DR1T_V_STARCHY_POTATO_CAL = 0;	DR1T_V_STARCHY_OTHER_CAL = 0;	DR1T_V_STARCHY_TOTAL_CAL = 0;	
		DR1T_V_OTHER_CAL = 0;			DR1T_V_TOTAL_CAL = 0;			DR1T_V_LEGUMES_CAL = 0;			DR1T_G_WHOLE_CAL = 0;
		DR1T_G_REFINED_CAL = 0;			DR1T_G_TOTAL_CAL = 0;			DR1T_PF_MEAT_CAL = 0;			DR1T_PF_CUREDMEAT_CAL = 0;
		DR1T_PF_ORGAN_CAL = 0;			DR1T_PF_POULT_CAL = 0;			DR1T_PF_SEAFD_HI_CAL = 0;		DR1T_PF_SEAFD_LOW_CAL = 0;
		DR1T_PF_MPS_TOTAL_CAL = 0;		DR1T_PF_EGGS_CAL = 0;			DR1T_PF_SOY_CAL = 0;			DR1T_PF_NUTSDS_CAL = 0;
		DR1T_PF_LEGUMES_CAL = 0;		DR1T_PF_TOTAL_CAL = 0;			DR1T_D_MILK_CAL = 0;			DR1T_D_YOGURT_CAL = 0;
		DR1T_D_CHEESE_CAL = 0;			DR1T_D_TOTAL_CAL = 0;			DR1T_OILS_CAL = 0;				DR1T_SOLID_FATS_CAL = 0;
		DR1T_ADD_SUGARS_CAL = 0;		DR1T_A_DRINKS_CAL = 0;

		DR2T_F_CITMLB_CAL = 0;			DR2T_F_OTHER_CAL = 0;			DR2T_F_JUICE_CAL = 0;	
		DR2T_F_TOTAL_CAL = 0;			DR2T_V_DRKGR_CAL = 0;			DR2T_V_REDOR_TOMATO_CAL = 0;	DR2T_V_REDOR_OTHER_CAL = 0;
		DR2T_V_REDOR_TOTAL_CAL = 0;		DR2T_V_STARCHY_POTATO_CAL = 0;	DR2T_V_STARCHY_OTHER_CAL = 0;	DR2T_V_STARCHY_TOTAL_CAL = 0;	
		DR2T_V_OTHER_CAL = 0;			DR2T_V_TOTAL_CAL = 0;			DR2T_V_LEGUMES_CAL = 0;			DR2T_G_WHOLE_CAL = 0;
		DR2T_G_REFINED_CAL = 0;			DR2T_G_TOTAL_CAL = 0;			DR2T_PF_MEAT_CAL = 0;			DR2T_PF_CUREDMEAT_CAL = 0;
		DR2T_PF_ORGAN_CAL = 0;			DR2T_PF_POULT_CAL = 0;			DR2T_PF_SEAFD_HI_CAL = 0;		DR2T_PF_SEAFD_LOW_CAL = 0;
		DR2T_PF_MPS_TOTAL_CAL = 0;		DR2T_PF_EGGS_CAL = 0;			DR2T_PF_SOY_CAL = 0;			DR2T_PF_NUTSDS_CAL = 0;
		DR2T_PF_LEGUMES_CAL = 0;		DR2T_PF_TOTAL_CAL = 0;			DR2T_D_MILK_CAL = 0;			DR2T_D_YOGURT_CAL = 0;
		DR2T_D_CHEESE_CAL = 0;			DR2T_D_TOTAL_CAL = 0;			DR2T_OILS_CAL = 0;				DR2T_SOLID_FATS_CAL = 0;
		DR2T_ADD_SUGARS_CAL = 0;		DR2T_A_DRINKS_CAL = 0;

		Day1STZ = 1;					Day2STZ = 1;
	end;
	if DayRec = 1 then do;
		if (DR1DRSTZ = 1) and (RIDAGEYR >= 20) then do;
			PERS_D1_GHGE = PERS_D1_GHGE + LN_GHGE; 
			PERS_D1_DGA1_GHGE = PERS_D1_DGA1_GHGE + LN_GHGE_DGA_1;									PERS_D1_DGA2_GHGE = PERS_D1_DGA2_GHGE + LN_GHGE_DGA_2;
			PERS_D1_DGA3_GHGE = PERS_D1_DGA3_GHGE + LN_GHGE_DGA_3;									PERS_D1_DGA4_GHGE = PERS_D1_DGA4_GHGE + LN_GHGE_DGA_4;
			PERS_D1_DGA5_GHGE = PERS_D1_DGA5_GHGE + LN_GHGE_DGA_5;						 			PERS_D1_DGA6_GHGE = PERS_D1_DGA6_GHGE + LN_GHGE_DGA_6;
			PERS_D1_DGA7_GHGE = PERS_D1_DGA7_GHGE + LN_GHGE_DGA_7;									PERS_D1_DGA8_GHGE = PERS_D1_DGA8_GHGE + LN_GHGE_DGA_8;
			PERS_D1_DGA9_GHGE = PERS_D1_DGA9_GHGE + LN_GHGE_DGA_9;									PERS_D1_DGA10_GHGE = PERS_D1_DGA10_GHGE + LN_GHGE_DGA_10;
			PERS_D1_DGA11_GHGE = PERS_D1_DGA11_GHGE + LN_GHGE_DGA_11;								PERS_D1_DGA12_GHGE = PERS_D1_DGA12_GHGE + LN_GHGE_DGA_12;
			PERS_D1_DGA13_GHGE = PERS_D1_DGA13_GHGE + LN_GHGE_DGA_13;								PERS_D1_DGA14_GHGE = PERS_D1_DGA14_GHGE + LN_GHGE_DGA_14;
			PERS_D1_DGA15_GHGE = PERS_D1_DGA15_GHGE + LN_GHGE_DGA_15;								PERS_D1_DGA16_GHGE = PERS_D1_DGA16_GHGE + LN_GHGE_DGA_16;
			PERS_D1_DGA17_GHGE = PERS_D1_DGA17_GHGE + LN_GHGE_DGA_17;								PERS_D1_DGA18_GHGE = PERS_D1_DGA18_GHGE + LN_GHGE_DGA_18;
			PERS_D1_DGA1_Gram = PERS_D1_DGA1_Gram + LN_Gram_DGA_1;									PERS_D1_DGA2_Gram = PERS_D1_DGA2_Gram + LN_Gram_DGA_2;
			PERS_D1_DGA3_Gram = PERS_D1_DGA3_Gram + LN_Gram_DGA_3;									PERS_D1_DGA4_Gram = PERS_D1_DGA4_Gram + LN_Gram_DGA_4;
			PERS_D1_DGA5_Gram = PERS_D1_DGA5_Gram + LN_Gram_DGA_5;						 			PERS_D1_DGA6_Gram = PERS_D1_DGA6_Gram + LN_Gram_DGA_6;
			PERS_D1_DGA7_Gram = PERS_D1_DGA7_Gram + LN_Gram_DGA_7;									PERS_D1_DGA8_Gram = PERS_D1_DGA8_Gram + LN_Gram_DGA_8;
			PERS_D1_DGA9_Gram = PERS_D1_DGA9_Gram + LN_Gram_DGA_9;									PERS_D1_DGA10_Gram = PERS_D1_DGA10_Gram + LN_Gram_DGA_10;
			PERS_D1_DGA11_Gram = PERS_D1_DGA11_Gram + LN_Gram_DGA_11;								PERS_D1_DGA12_Gram = PERS_D1_DGA12_Gram + LN_Gram_DGA_12;
			PERS_D1_DGA13_Gram = PERS_D1_DGA13_Gram + LN_Gram_DGA_13;								PERS_D1_DGA14_Gram = PERS_D1_DGA14_Gram + LN_Gram_DGA_14;
			PERS_D1_DGA15_Gram = PERS_D1_DGA15_Gram + LN_Gram_DGA_15;								PERS_D1_DGA16_Gram = PERS_D1_DGA16_Gram + LN_Gram_DGA_16;
			PERS_D1_DGA17_Gram = PERS_D1_DGA17_Gram + LN_Gram_DGA_17;								PERS_D1_DGA18_Gram = PERS_D1_DGA18_Gram + LN_Gram_DGA_18;

			DR1T_F_CITMLB_CAL = DR1T_F_CITMLB_CAL + DR1I_F_CITMLB_CAL;
			DR1T_F_OTHER_CAL = DR1T_F_OTHER_CAL + DR1I_F_OTHER_CAL;									DR1T_F_JUICE_CAL = DR1T_F_JUICE_CAL + DR1I_F_JUICE_CAL;	
			DR1T_F_TOTAL_CAL = DR1T_F_TOTAL_CAL + DR1I_F_TOTAL_CAL;									DR1T_V_DRKGR_CAL = DR1T_V_DRKGR_CAL + DR1I_V_DRKGR_CAL;				
			DR1T_V_REDOR_TOMATO_CAL = DR1T_V_REDOR_TOMATO_CAL + DR1I_V_REDOR_TOMATO_CAL;			DR1T_V_REDOR_OTHER_CAL = DR1T_V_REDOR_OTHER_CAL + DR1I_V_REDOR_OTHER_CAL;											
			DR1T_V_REDOR_TOTAL_CAL = DR1T_V_REDOR_TOTAL_CAL + DR1I_V_REDOR_TOTAL_CAL;				DR1T_V_STARCHY_POTATO_CAL = DR1T_V_STARCHY_POTATO_CAL + DR1I_V_STARCHY_POTATO_CAL;		
			DR1T_V_STARCHY_OTHER_CAL = DR1T_V_STARCHY_OTHER_CAL + DR1I_V_STARCHY_OTHER_CAL;			DR1T_V_STARCHY_TOTAL_CAL = DR1T_V_STARCHY_TOTAL_CAL + DR1I_V_STARCHY_TOTAL_CAL;			
			DR1T_V_OTHER_CAL = DR1T_V_OTHER_CAL + DR1I_V_OTHER_CAL;									DR1T_V_TOTAL_CAL = DR1T_V_TOTAL_CAL + DR1I_V_TOTAL_CAL;									
			DR1T_V_LEGUMES_CAL = DR1T_V_LEGUMES_CAL + DR1I_V_LEGUMES_CAL;							DR1T_G_WHOLE_CAL = DR1T_G_WHOLE_CAL + DR1I_G_WHOLE_CAL;									
			DR1T_G_REFINED_CAL = DR1T_G_REFINED_CAL + DR1I_G_REFINED_CAL;							DR1T_G_TOTAL_CAL = DR1T_G_TOTAL_CAL + DR1I_G_TOTAL_CAL;									
			DR1T_PF_MEAT_CAL = DR1T_PF_MEAT_CAL + DR1I_PF_MEAT_CAL;									DR1T_PF_CUREDMEAT_CAL = DR1T_PF_CUREDMEAT_CAL + DR1I_PF_CUREDMEAT_CAL;					
			DR1T_PF_ORGAN_CAL = DR1T_PF_ORGAN_CAL + DR1I_PF_ORGAN_CAL;								DR1T_PF_POULT_CAL = DR1T_PF_POULT_CAL + DR1I_PF_POULT_CAL;								
			DR1T_PF_SEAFD_HI_CAL = DR1T_PF_SEAFD_HI_CAL + DR1I_PF_SEAFD_HI_CAL;						DR1T_PF_SEAFD_LOW_CAL = DR1T_PF_SEAFD_LOW_CAL + DR1I_PF_SEAFD_LOW_CAL;					
			DR1T_PF_MPS_TOTAL_CAL = DR1T_PF_MPS_TOTAL_CAL + DR1I_PF_MPS_TOTAL_CAL;					DR1T_PF_EGGS_CAL = DR1T_PF_EGGS_CAL + DR1I_PF_EGGS_CAL;									
			DR1T_PF_SOY_CAL = DR1T_PF_SOY_CAL + DR1I_PF_SOY_CAL;									DR1T_PF_NUTSDS_CAL = DR1T_PF_NUTSDS_CAL + DR1I_PF_NUTSDS_CAL;							
			DR1T_PF_LEGUMES_CAL = DR1T_PF_LEGUMES_CAL + DR1I_PF_LEGUMES_CAL;						DR1T_PF_TOTAL_CAL = DR1T_PF_TOTAL_CAL + DR1I_PF_TOTAL_CAL;								
			DR1T_D_MILK_CAL = DR1T_D_MILK_CAL + DR1I_D_MILK_CAL;									DR1T_D_YOGURT_CAL = DR1T_D_YOGURT_CAL + DR1I_D_YOGURT_CAL;								
			DR1T_D_CHEESE_CAL = DR1T_D_CHEESE_CAL + DR1I_D_CHEESE_CAL;								DR1T_D_TOTAL_CAL = DR1T_D_TOTAL_CAL + DR1I_D_TOTAL_CAL;									
			DR1T_OILS_CAL = DR1T_OILS_CAL + DR1I_OILS_CAL;											DR1T_SOLID_FATS_CAL = DR1T_SOLID_FATS_CAL + DR1I_SOLID_FATS_CAL;						
			DR1T_ADD_SUGARS_CAL = DR1T_ADD_SUGARS_CAL + DR1I_ADD_SUGARS_CAL;						DR1T_A_DRINKS_CAL = DR1T_A_DRINKS_CAL + DR1I_A_DRINKS_CAL;
		end;
		Day1STZ = DR1DRSTZ;
	end;
	if DayRec = 2 then do;
		if (DR1DRSTZ = 1) and (RIDAGEYR >= 20) then do;
			PERS_D2_GHGE = PERS_D2_GHGE + LN_GHGE;  
			PERS_D2_DGA1_GHGE = PERS_D2_DGA1_GHGE + LN_GHGE_DGA_1;									PERS_D2_DGA2_GHGE = PERS_D2_DGA2_GHGE + LN_GHGE_DGA_2;
			PERS_D2_DGA3_GHGE = PERS_D2_DGA3_GHGE + LN_GHGE_DGA_3;									PERS_D2_DGA4_GHGE = PERS_D2_DGA4_GHGE + LN_GHGE_DGA_4;
			PERS_D2_DGA5_GHGE = PERS_D2_DGA5_GHGE + LN_GHGE_DGA_5;						 			PERS_D2_DGA6_GHGE = PERS_D2_DGA6_GHGE + LN_GHGE_DGA_6;
			PERS_D2_DGA7_GHGE = PERS_D2_DGA7_GHGE + LN_GHGE_DGA_7;									PERS_D2_DGA8_GHGE = PERS_D2_DGA8_GHGE + LN_GHGE_DGA_8;
			PERS_D2_DGA9_GHGE = PERS_D2_DGA9_GHGE + LN_GHGE_DGA_9;									PERS_D2_DGA10_GHGE = PERS_D2_DGA10_GHGE + LN_GHGE_DGA_10;
			PERS_D2_DGA11_GHGE = PERS_D2_DGA11_GHGE + LN_GHGE_DGA_11;								PERS_D2_DGA12_GHGE = PERS_D2_DGA12_GHGE + LN_GHGE_DGA_12;
			PERS_D2_DGA13_GHGE = PERS_D2_DGA13_GHGE + LN_GHGE_DGA_13;								PERS_D2_DGA14_GHGE = PERS_D2_DGA14_GHGE + LN_GHGE_DGA_14;
			PERS_D2_DGA15_GHGE = PERS_D2_DGA15_GHGE + LN_GHGE_DGA_15;								PERS_D2_DGA16_GHGE = PERS_D2_DGA16_GHGE + LN_GHGE_DGA_16;
			PERS_D2_DGA17_GHGE = PERS_D2_DGA17_GHGE + LN_GHGE_DGA_17;								PERS_D2_DGA18_GHGE = PERS_D2_DGA18_GHGE + LN_GHGE_DGA_18;
			PERS_D2_DGA1_Gram = PERS_D2_DGA1_Gram + LN_Gram_DGA_1;									PERS_D2_DGA2_Gram = PERS_D2_DGA2_Gram + LN_Gram_DGA_2;
			PERS_D2_DGA3_Gram = PERS_D2_DGA3_Gram + LN_Gram_DGA_3;									PERS_D2_DGA4_Gram = PERS_D2_DGA4_Gram + LN_Gram_DGA_4;
			PERS_D2_DGA5_Gram = PERS_D2_DGA5_Gram + LN_Gram_DGA_5;						 			PERS_D2_DGA6_Gram = PERS_D2_DGA6_Gram + LN_Gram_DGA_6;
			PERS_D2_DGA7_Gram = PERS_D2_DGA7_Gram + LN_Gram_DGA_7;									PERS_D2_DGA8_Gram = PERS_D2_DGA8_Gram + LN_Gram_DGA_8;
			PERS_D2_DGA9_Gram = PERS_D2_DGA9_Gram + LN_Gram_DGA_9;									PERS_D2_DGA10_Gram = PERS_D2_DGA10_Gram + LN_Gram_DGA_10;
			PERS_D2_DGA11_Gram = PERS_D2_DGA11_Gram + LN_Gram_DGA_11;								PERS_D2_DGA12_Gram = PERS_D2_DGA12_Gram + LN_Gram_DGA_12;
			PERS_D2_DGA13_Gram = PERS_D2_DGA13_Gram + LN_Gram_DGA_13;								PERS_D2_DGA14_Gram = PERS_D2_DGA14_Gram + LN_Gram_DGA_14;
			PERS_D2_DGA15_Gram = PERS_D2_DGA15_Gram + LN_Gram_DGA_15;								PERS_D2_DGA16_Gram = PERS_D2_DGA16_Gram + LN_Gram_DGA_16;
			PERS_D2_DGA17_Gram = PERS_D2_DGA17_Gram + LN_Gram_DGA_17;								PERS_D2_DGA18_Gram = PERS_D2_DGA18_Gram + LN_Gram_DGA_18;

			DR2T_F_CITMLB_CAL = DR2T_F_CITMLB_CAL + DR1I_F_CITMLB_CAL;
			DR2T_F_OTHER_CAL = DR2T_F_OTHER_CAL + DR1I_F_OTHER_CAL;									DR2T_F_JUICE_CAL = DR2T_F_JUICE_CAL + DR1I_F_JUICE_CAL;	
			DR2T_F_TOTAL_CAL = DR2T_F_TOTAL_CAL + DR1I_F_TOTAL_CAL;									DR2T_V_DRKGR_CAL = DR2T_V_DRKGR_CAL + DR1I_V_DRKGR_CAL;
			DR2T_V_REDOR_TOMATO_CAL = DR2T_V_REDOR_TOMATO_CAL + DR1I_V_REDOR_TOMATO_CAL;			DR2T_V_REDOR_OTHER_CAL = DR2T_V_REDOR_OTHER_CAL + DR1I_V_REDOR_OTHER_CAL;		
			DR1T_V_REDOR_TOTAL_CAL = DR1T_V_REDOR_TOTAL_CAL + DR1I_V_REDOR_TOTAL_CAL;				DR2T_V_STARCHY_POTATO_CAL = DR2T_V_STARCHY_POTATO_CAL + DR1I_V_STARCHY_POTATO_CAL;	
			DR2T_V_STARCHY_OTHER_CAL = DR2T_V_STARCHY_OTHER_CAL + DR1I_V_STARCHY_OTHER_CAL;			DR2T_V_STARCHY_TOTAL_CAL = DR2T_V_STARCHY_TOTAL_CAL + DR1I_V_STARCHY_TOTAL_CAL;
			DR2T_V_OTHER_CAL = DR2T_V_OTHER_CAL + DR1I_V_OTHER_CAL;									DR2T_V_TOTAL_CAL = DR2T_V_TOTAL_CAL + DR1I_V_TOTAL_CAL;	
			DR2T_V_LEGUMES_CAL = DR2T_V_LEGUMES_CAL + DR1I_V_LEGUMES_CAL;							DR2T_G_WHOLE_CAL = DR2T_G_WHOLE_CAL + DR1I_G_WHOLE_CAL;	
			DR2T_G_REFINED_CAL = DR2T_G_REFINED_CAL + DR1I_G_REFINED_CAL;							DR2T_G_TOTAL_CAL = DR2T_G_TOTAL_CAL + DR1I_G_TOTAL_CAL;								
			DR2T_PF_MEAT_CAL = DR2T_PF_MEAT_CAL + DR1I_PF_MEAT_CAL;									DR2T_PF_CUREDMEAT_CAL = DR2T_PF_CUREDMEAT_CAL + DR1I_PF_CUREDMEAT_CAL;				
			DR2T_PF_ORGAN_CAL = DR2T_PF_ORGAN_CAL + DR1I_PF_ORGAN_CAL;								DR2T_PF_POULT_CAL = DR2T_PF_POULT_CAL + DR1I_PF_POULT_CAL;							
			DR2T_PF_SEAFD_HI_CAL = DR2T_PF_SEAFD_HI_CAL + DR1I_PF_SEAFD_HI_CAL;						DR2T_PF_SEAFD_LOW_CAL = DR2T_PF_SEAFD_LOW_CAL + DR1I_PF_SEAFD_LOW_CAL;				
			DR2T_PF_MPS_TOTAL_CAL = DR2T_PF_MPS_TOTAL_CAL + DR1I_PF_MPS_TOTAL_CAL;					DR2T_PF_EGGS_CAL = DR2T_PF_EGGS_CAL + DR1I_PF_EGGS_CAL;								
			DR2T_PF_SOY_CAL = DR2T_PF_SOY_CAL + DR1I_PF_SOY_CAL;									DR2T_PF_NUTSDS_CAL = DR2T_PF_NUTSDS_CAL + DR1I_PF_NUTSDS_CAL;					
			DR2T_PF_LEGUMES_CAL = DR2T_PF_LEGUMES_CAL + DR1I_PF_LEGUMES_CAL;						DR2T_PF_TOTAL_CAL = DR2T_PF_TOTAL_CAL + DR1I_PF_TOTAL_CAL;						
			DR2T_D_MILK_CAL = DR2T_D_MILK_CAL + DR1I_D_MILK_CAL;									DR2T_D_YOGURT_CAL = DR2T_D_YOGURT_CAL + DR1I_D_YOGURT_CAL;						
			DR2T_D_CHEESE_CAL = DR2T_D_CHEESE_CAL + DR1I_D_CHEESE_CAL;								DR2T_D_TOTAL_CAL = DR2T_D_TOTAL_CAL + DR1I_D_TOTAL_CAL;							
			DR2T_OILS_CAL = DR2T_OILS_CAL + DR1I_OILS_CAL;											DR2T_SOLID_FATS_CAL = DR2T_SOLID_FATS_CAL + DR1I_SOLID_FATS_CAL;				
			DR2T_ADD_SUGARS_CAL = DR2T_ADD_SUGARS_CAL + DR1I_ADD_SUGARS_CAL;						DR2T_A_DRINKS_CAL = DR2T_A_DRINKS_CAL + DR1I_A_DRINKS_CAL;
		end;
		Day2STZ = DR1DRSTZ;
	end;
	if last.SEQN;
Run;


*Clean up variables for individual foods;
Data INDPERS_OUT;
	set INDPERS_OUT;
	drop DR1ILINE DR1IFDCD DR1MC DR1IGRMS DR1IKCAL DR1ISFAT DR1IMFAT DR1IPFAT DR1ISODI DR1IKCAL_CAL DR1ISFAT_CAL DR1IMFAT_CAL DR1IPFAT_CAL DR1IPROT_CAL DR1ITFAT_CAL DR1ICARB_CAL DR1ISODI_CAL Description;
	drop DR1I_F_CITMLB_CAL DR1I_F_OTHER_CAL DR1I_F_JUICE_CAL DR1I_F_TOTAL_CAL DR1I_V_DRKGR_CAL DR1I_V_REDOR_TOMATO_CAL DR1I_V_REDOR_OTHER_CAL DR1I_V_REDOR_TOTAL_CAL DR1I_V_STARCHY_POTATO_CAL;
	drop DR1I_V_STARCHY_OTHER_CAL DR1I_V_STARCHY_TOTAL_CAL DR1I_V_OTHER_CAL DR1I_V_TOTAL_CAL DR1I_V_LEGUMES_CAL DR1I_G_WHOLE_CAL DR1I_G_REFINED_CAL DR1I_G_TOTAL_CAL DR1I_PF_MEAT_CAL DR1I_PF_CUREDMEAT_CAL;
	drop DR1I_PF_ORGAN_CAL DR1I_PF_POULT_CAL DR1I_PF_SEAFD_HI_CAL DR1I_PF_SEAFD_LOW_CAL DR1I_PF_MPS_TOTAL_CAL DR1I_PF_EGGS_CAL DR1I_PF_SOY_CAL DR1I_PF_NUTSDS_CAL DR1I_PF_LEGUMES_CAL DR1I_PF_TOTAL_CAL;
	drop DR1I_D_MILK_CAL DR1I_D_YOGURT_CAL DR1I_D_CHEESE_CAL DR1I_D_TOTAL_CAL DR1I_OILS_CAL DR1I_SOLID_FATS_CAL DR1I_ADD_SUGARS_CAL DR1I_A_DRINKS_CAL;
Run;
Data INDPERS_OUT;
	set INDPERS_OUT;
	if (Day1STZ = 1) and (Day2STZ = 1) and (RIDAGEYR >= 20) then do;
		PERS_AV_GHGE = (PERS_D1_GHGE + PERS_D2_GHGE) / 2;
		PERS_AV_DGA1_GHGE = (PERS_D1_DGA1_GHGE + PERS_D2_DGA1_GHGE) / 2;							PERS_AV_DGA2_GHGE = (PERS_D1_DGA2_GHGE + PERS_D2_DGA2_GHGE) / 2;
		PERS_AV_DGA3_GHGE = (PERS_D1_DGA3_GHGE + PERS_D2_DGA3_GHGE) / 2;							PERS_AV_DGA4_GHGE = (PERS_D1_DGA4_GHGE + PERS_D2_DGA4_GHGE) / 2;
		PERS_AV_DGA5_GHGE = (PERS_D1_DGA5_GHGE + PERS_D2_DGA5_GHGE) / 2;							PERS_AV_DGA6_GHGE = (PERS_D1_DGA6_GHGE + PERS_D2_DGA6_GHGE) / 2;
		PERS_AV_DGA7_GHGE = (PERS_D1_DGA7_GHGE + PERS_D2_DGA7_GHGE) / 2;							PERS_AV_DGA8_GHGE = (PERS_D1_DGA8_GHGE + PERS_D2_DGA8_GHGE) / 2;
		PERS_AV_DGA9_GHGE = (PERS_D1_DGA9_GHGE + PERS_D2_DGA9_GHGE) / 2;							PERS_AV_DGA10_GHGE = (PERS_D1_DGA10_GHGE + PERS_D2_DGA10_GHGE) / 2;
		PERS_AV_DGA11_GHGE = (PERS_D1_DGA11_GHGE + PERS_D2_DGA11_GHGE) / 2;							PERS_AV_DGA12_GHGE = (PERS_D1_DGA12_GHGE + PERS_D2_DGA12_GHGE) / 2;
		PERS_AV_DGA13_GHGE = (PERS_D1_DGA13_GHGE + PERS_D2_DGA13_GHGE) / 2;							PERS_AV_DGA14_GHGE = (PERS_D1_DGA14_GHGE + PERS_D2_DGA14_GHGE) / 2;
		PERS_AV_DGA15_GHGE = (PERS_D1_DGA15_GHGE + PERS_D2_DGA15_GHGE) / 2;							PERS_AV_DGA16_GHGE = (PERS_D1_DGA16_GHGE + PERS_D2_DGA16_GHGE) / 2;
		PERS_AV_DGA17_GHGE = (PERS_D1_DGA17_GHGE + PERS_D2_DGA17_GHGE) / 2;							PERS_AV_DGA18_GHGE = (PERS_D1_DGA18_GHGE + PERS_D2_DGA18_GHGE) / 2;	
		PERS_AV_DGA1_Gram = (PERS_D1_DGA1_Gram + PERS_D2_DGA1_Gram) / 2;							PERS_AV_DGA2_Gram = (PERS_D1_DGA2_Gram + PERS_D2_DGA2_Gram) / 2;
		PERS_AV_DGA3_Gram = (PERS_D1_DGA3_Gram + PERS_D2_DGA3_Gram) / 2;							PERS_AV_DGA4_Gram = (PERS_D1_DGA4_Gram + PERS_D2_DGA4_Gram) / 2;
		PERS_AV_DGA5_Gram = (PERS_D1_DGA5_Gram + PERS_D2_DGA5_Gram) / 2;							PERS_AV_DGA6_Gram = (PERS_D1_DGA6_Gram + PERS_D2_DGA6_Gram) / 2;
		PERS_AV_DGA7_Gram = (PERS_D1_DGA7_Gram + PERS_D2_DGA7_Gram) / 2;							PERS_AV_DGA8_Gram = (PERS_D1_DGA8_Gram + PERS_D2_DGA8_Gram) / 2;
		PERS_AV_DGA9_Gram = (PERS_D1_DGA9_Gram + PERS_D2_DGA9_Gram) / 2;							PERS_AV_DGA10_Gram = (PERS_D1_DGA10_Gram + PERS_D2_DGA10_Gram) / 2;
		PERS_AV_DGA11_Gram = (PERS_D1_DGA11_Gram + PERS_D2_DGA11_Gram) / 2;							PERS_AV_DGA12_Gram = (PERS_D1_DGA12_Gram + PERS_D2_DGA12_Gram) / 2;
		PERS_AV_DGA13_Gram = (PERS_D1_DGA13_Gram + PERS_D2_DGA13_Gram) / 2;							PERS_AV_DGA14_Gram = (PERS_D1_DGA14_Gram + PERS_D2_DGA14_Gram) / 2;
		PERS_AV_DGA15_Gram = (PERS_D1_DGA15_Gram + PERS_D2_DGA15_Gram) / 2;							PERS_AV_DGA16_Gram = (PERS_D1_DGA16_Gram + PERS_D2_DGA16_Gram) / 2;
		PERS_AV_DGA17_Gram = (PERS_D1_DGA17_Gram + PERS_D2_DGA17_Gram) / 2;							PERS_AV_DGA18_Gram = (PERS_D1_DGA18_Gram + PERS_D2_DGA18_Gram) / 2;	

		DRXT_F_CITMLB_CAL = (DR1T_F_CITMLB_CAL + DR2T_F_CITMLB_CAL) / 2;
		DRXT_F_OTHER_CAL = (DR1T_F_OTHER_CAL + DR2T_F_OTHER_CAL) / 2;								DRXT_F_JUICE_CAL = (DR1T_F_JUICE_CAL + DR2T_F_JUICE_CAL) / 2;
		DRXT_F_TOTAL_CAL = (DR1T_F_TOTAL_CAL + DR2T_F_TOTAL_CAL) / 2;								DRXT_V_DRKGR_CAL = (DR1T_V_DRKGR_CAL + DR2T_V_DRKGR_CAL) / 2;
		DRXT_V_REDOR_TOMATO_CAL = (DR1T_V_REDOR_TOMATO_CAL + DR2T_V_REDOR_TOMATO_CAL) / 2;			DRXT_V_REDOR_OTHER_CAL = (DR1T_V_REDOR_OTHER_CAL + DR2T_V_REDOR_OTHER_CAL) / 2;
		DRXT_V_REDOR_TOTAL_CAL = (DR1T_V_REDOR_TOTAL_CAL + DR2T_V_REDOR_TOTAL_CAL) / 2;				DRXT_V_STARCHY_POTATO_CAL = (DR1T_V_STARCHY_POTATO_CAL + DR2T_V_STARCHY_POTATO_CAL) / 2;
		DRXT_V_STARCHY_OTHER_CAL = (DR1T_V_STARCHY_OTHER_CAL + DR2T_V_STARCHY_OTHER_CAL) / 2;		DRXT_V_STARCHY_TOTAL_CAL = (DR1T_V_STARCHY_TOTAL_CAL + DR2T_V_STARCHY_TOTAL_CAL) / 2;
		DRXT_V_OTHER_CAL = (DR1T_V_OTHER_CAL + DR2T_V_OTHER_CAL) / 2;								DRXT_V_TOTAL_CAL = (DR1T_V_TOTAL_CAL + DR2T_V_TOTAL_CAL) / 2;
		DRXT_V_LEGUMES_CAL = (DR1T_V_LEGUMES_CAL + DR2T_V_LEGUMES_CAL) / 2;							DRXT_G_WHOLE_CAL = (DR1T_G_WHOLE_CAL + DR2T_G_WHOLE_CAL) / 2;
		DRXT_G_REFINED_CAL = (DR1T_G_REFINED_CAL + DR2T_G_REFINED_CAL) / 2;							DRXT_G_TOTAL_CAL = (DR1T_G_TOTAL_CAL + DR2T_G_TOTAL_CAL) / 2;
		DRXT_PF_MEAT_CAL = (DR1T_PF_MEAT_CAL + DR2T_PF_MEAT_CAL) / 2;								DRXT_PF_CUREDMEAT_CAL = (DR1T_PF_CUREDMEAT_CAL + DR2T_PF_CUREDMEAT_CAL) / 2;
		DRXT_PF_ORGAN_CAL = (DR1T_PF_ORGAN_CAL + DR2T_PF_ORGAN_CAL) / 2;							DRXT_PF_POULT_CAL = (DR1T_PF_POULT_CAL + DR2T_PF_POULT_CAL) / 2;
		DRXT_PF_SEAFD_HI_CAL = (DR1T_PF_SEAFD_HI_CAL + DR2T_PF_SEAFD_HI_CAL) / 2;					DRXT_PF_SEAFD_LOW_CAL = (DR1T_PF_SEAFD_LOW_CAL + DR2T_PF_SEAFD_LOW_CAL) / 2;
		DRXT_PF_MPS_TOTAL_CAL = (DR1T_PF_MPS_TOTAL_CAL + DR2T_PF_MPS_TOTAL_CAL) / 2;				DRXT_PF_EGGS_CAL = (DR1T_PF_EGGS_CAL + DR2T_PF_EGGS_CAL) / 2;
		DRXT_PF_SOY_CAL = (DR1T_PF_SOY_CAL + DR2T_PF_SOY_CAL) / 2;									DRXT_PF_NUTSDS_CAL = (DR1T_PF_NUTSDS_CAL + DR2T_PF_NUTSDS_CAL) / 2;
		DRXT_PF_LEGUMES_CAL = (DR1T_PF_LEGUMES_CAL + DR2T_PF_LEGUMES_CAL) / 2;						DRXT_PF_TOTAL_CAL = (DR1T_PF_TOTAL_CAL + DR2T_PF_TOTAL_CAL) / 2;
		DRXT_D_MILK_CAL = (DR1T_D_MILK_CAL + DR2T_D_MILK_CAL) / 2;									DRXT_D_YOGURT_CAL = (DR1T_D_YOGURT_CAL + DR2T_D_YOGURT_CAL) / 2;
		DRXT_D_CHEESE_CAL = (DR1T_D_CHEESE_CAL + DR2T_D_CHEESE_CAL) / 2;							DRXT_D_TOTAL_CAL = (DR1T_D_TOTAL_CAL + DR2T_D_TOTAL_CAL) / 2;
		DRXT_OILS_CAL = (DR1T_OILS_CAL + DR2T_OILS_CAL) / 2;										DRXT_SOLID_FATS_CAL = (DR1T_SOLID_FATS_CAL + DR2T_SOLID_FATS_CAL) / 2;
		DRXT_ADD_SUGARS_CAL = (DR1T_ADD_SUGARS_CAL + DR2T_ADD_SUGARS_CAL) / 2;						DRXT_A_DRINKS_CAL = (DR1T_A_DRINKS_CAL + DR2T_A_DRINKS_CAL) / 2;
	end;
Run;
*average£»
