%macro CreatDS(cyclein, DS); *Macro to import NHANES database from files;
	%let cycle = %substr(&cyclein,2,%eval(%length(&cyclein)-2));		%let path = D:/nhanes/data/;		filename xptIn "&path.&DS..xpt";			libname xptIn xport;
	data SASdata.&DS;	set xptIn.&DS;	run;
%mend creatds;
libname SASdata "D:\CF\data\";
%CreatDS("2011_2012",DR1TOT_G);	%CreatDS("2011_2012",DR2TOT_G);	
%CreatDS("2013_2014",DR1TOT_H);	%CreatDS("2013_2014",DR2TOT_H);	%CreatDS("2015_2016",DR1TOT_I);	%CreatDS("2015_2016",DR2TOT_I);	
%CreatDS("2017_2020",P_DR1TOT);	%CreatDS("2017_2020",P_DR2TOT);

Data TOT_merge;
	merge 	SASdata.DR1TOT_G SASdata.DR2TOT_G SASdata.DR1TOT_H SASdata.DR2TOT_H 
			SASdata.DR1TOT_I SASdata.DR2TOT_I SASdata.P_DR1TOT SASdata.P_DR2TOT;
	by SEQN;
Run;

Data TOT_merge;
	set TOT_merge;
	DRXTKCAL = (DR1TKCAL + DR2TKCAL) / 2;	*Total Energy (kcal);
	DRXTPROT = (DR1TPROT + DR2TPROT) / 2;	*Total Protein (g);
	DRXTCARB = (DR1TCARB + DR2TCARB) / 2;	*Total Carbohydrate (g);
	DRXTSUGR = (DR1TSUGR + DR2TSUGR) / 2;	*Total Sugar (g);
	DRXTFIBE = (DR1TFIBE + DR2TFIBE) / 2;	*Dietary Fiber (g);
	DRXTTFAT = (DR1TTFAT + DR2TTFAT) / 2;	*Total Fat (g);
	DRXTSFAT = (DR1TSFAT + DR2TSFAT) / 2;	*Saturated Fat (g);
	DRXTMFAT = (DR1TMFAT + DR2TMFAT) / 2;	*Monounsaturated Fat (g);
	DRXTPFAT = (DR1TPFAT + DR2TPFAT) / 2;	*Polyunsaturated Fat (g);
	DRXTCHOL = (DR1TCHOL + DR2TCHOL) / 2;	*Cholesterol (mg);
	DRXTATOC = (DR1TATOC + DR2TATOC) / 2;	*Vitamin E as alpha-tocopherol (mg);
	DRXTATOA = (DR1TATOA + DR2TATOA) / 2;	*Added alpha-tocopherol (Vitamin E) (mg);
	DRXTRET	 = (DR1TRET  + DR2TRET)  / 2;	*Retinol (ug);
	DRXTVARA = (DR1TVARA + DR2TVARA) / 2;	*Vitamin A, RAE (ug);
	DRXTACAR = (DR1TACAR + DR2TACAR) / 2;	*Alpha-carotene (ug);
	DRXTBCAR = (DR1TBCAR + DR2TBCAR) / 2;	*Beta-carotene (ug);
	DRXTCRYP = (DR1TCRYP + DR2TCRYP) / 2;	*Beta-cryptoxanthin (ug);
	DRXTLYCO = (DR1TLYCO + DR2TLYCO) / 2;	*Lycopene (ug);
	DRXTLZ	 = (DR1TLZ   + DR2TLZ)   / 2;	*Lutein + zeaxanthin (ug);
	DRXTVB1  = (DR1TVB1  + DR2TVB1)  / 2;	*Vitamin B1 (mg);
	DRXTVB2  = (DR1TVB2  + DR2TVB2)  / 2;	*Vitamin B2 (mg);
	DRXTNIAC = (DR1TNIAC + DR2TNIAC) / 2;	*Niacin (mg);
	DRXTVB6  = (DR1TVB6  + DR2TVB6)  / 2;	*Vitamin B6 (mg);
	DRXTFOLA = (DR1TFOLA + DR2TFOLA) / 2;	*Total folate (ug);
	DRXTFA   = (DR1TFA   + DR2TFA)   / 2;	*Folic acid (ug);
	DRXTFF   = (DR1TFF   + DR2TFF)   / 2;	*Food folate (ug);
	DRXTFDFE = (DR1TFDFE + DR2TFDFE) / 2;	*Folate, DFE (ug);
	DRXTCHL  = (DR1TCHL  + DR2TCHL)  / 2;	*Total choline (mg);
	DRXTVB12 = (DR1TVB12 + DR2TVB12) / 2;	*Vitamin B12;
	DRXTB12A = (DR1TB12A + DR2TB12A) / 2;	*Added vitamin B12 (ug);
	DRXTVC   = (DR1TVC   + DR2TVC)   / 2;	*Vitamin C (mg);
	*DRXTVD   = (DR1TVD   + DR2TVD)   / 2;	*Vitamin D (ug);
	DRXTVK   = (DR1TVK   + DR2TVK)   / 2;	*Vitamin K (ug);
	DRXTCALC = (DR1TCALC + DR2TCALC) / 2;	*Calcium (mg);
	DRXTPHOS = (DR1TPHOS + DR2TPHOS) / 2;	*Phosphorus (mg);
	DRXTMAGN = (DR1TMAGN + DR2TMAGN) / 2;	*Magnesium (mg);
	DRXTIRON = (DR1TIRON + DR2TIRON) / 2;	*Iron (mg);
	DRXTZINC = (DR1TZINC + DR2TZINC) / 2;	*Zinc (mg);
	DRXTCOPP = (DR1TCOPP + DR2TCOPP) / 2;	*Copper (mg);
	DRXTSODI = (DR1TSODI + DR2TSODI) / 2 / 1000;	*Sodium (g);
	DRXTPOTA = (DR1TPOTA + DR2TPOTA) / 2;	*Potassium (mg);
	DRXTSELE = (DR1TSELE + DR2TSELE) / 2;	*Selenium (ug);
	DRXTCAFF = (DR1TCAFF + DR2TCAFF) / 2;	*Caffeine (mg);
	DRXTTHEO = (DR1TTHEO + DR2TTHEO) / 2;	*Theobromine (mg);
	DRXTALCO = (DR1TALCO + DR2TALCO) / 2;	*Alcohol (g);
	DRXDRSTZ = (DR1DRSTZ + DR2DRSTZ) / 2;
Run;

